### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '<'. run in google colab

### ISSUE THREAD

**Issue by kirdik** [xinntao/ESRGAN#122]
I'm trying to run in google colab. Basic startup throws this error. All models are downloaded and placed in the model folder.
`python test.py`
`Traceback (most recent call last):
  File "test.py", line 15, in <module>
    model.load_state_dict(torch.load(model_path), strict=True)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.`

**Comment by Jeejo-Joy** [comment]
Getting this same error with google collab, however it works locally.

In I tried loading directly from pickle still same error.

<img width="1451" alt="image" src="https://user-images.githubusercontent.com/34362570/157726426-8ff11170-0672-46b7-bcbf-3829740a920b.png">

**Comment by Jeromedebruyn** [comment]
> 

@kirdik I have the same error, did you every manage to solve it?

**Comment by DuyguSerbes** [comment]
Hello, did you solve the problem? I am getting the same error.

**Comment by Haadia-a** [comment]
@kirdik @Jeejo-Joy did you guys manage to find a solution? Please share
