### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8d in position 9: invalid start byte

### ISSUE THREAD

**Issue by Madxbio97** [xinntao/ESRGAN#21]
Then I want to lauch test.py I have this error: 
''Traceback (most recent call last):
  File "test.py", line 21, in <module>
    model = model.to(device)
  File "C:\Users\Никита_Владимир-ПК\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 381, in to
    return self._apply(convert)
  File "C:\Users\Никита_Владимир-ПК\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  File "C:\Users\Никита_Владимир-ПК\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  File "C:\Users\Никита_Владимир-ПК\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 193, in _apply
    param.data = fn(param.data)
  File "C:\Users\Никита_Владимир-ПК\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 379, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "C:\Users\Никита_Владимир-ПК\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\cuda\__init__.py", line 163, in _lazy_init
    _cudart = _load_cudart()
  File "C:\Users\Никита_Владимир-ПК\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\cuda\__init__.py", line 60, in _load_cudart
    lib = find_cuda_windows_lib()
  File "C:\Users\Никита_Владимир-ПК\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\cuda\__init__.py", line 33, in find_cuda_windows_lib
    out = out.decode().strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8d in position 9: invalid start byte''
Why this is happening ? Tell me please. My PC spec`s^
Windows 10
AMD Ryzen 2400g 3.89 Ghz
Geforce 1060 4 GB
8 GB RAM

**Comment by Madxbio97** [comment]
problem solved.
On the way to Python, its modules, and PIP should not be Cyrillic.
