### ISSUE TITLE
    import architecture as arch error

### ISSUE THREAD

**Issue by Praddmobile** [xinntao/ESRGAN#27]
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    import architecture as arch
  File "/User/1/ESRGAN-master/architecture.py", line 33
    self.model = B.sequential(fea_conv, B.ShortcutBlock(B.sequential(*rb_blocks, LR_conv)),\
SyntaxError: only named arguments may follow *expression

**Comment by Praddmobile** [comment]
> I have not encounter this problem.
> Is it from python 2. I am using python3.6/3.7

first i was on 2.7 then i linked python 3.7. i had it installed but not linked.
i'm using mac os mojave.

**Comment by xinntao** [comment]
So when you use pytorch 3.7, still have this problem?

**Comment by Praddmobile** [comment]
> So when you use pytorch 3.7, still have this problem?

you mean python 3.7? yes, still same problem

**Comment by xinntao** [comment]
Emm, I have no idea. You need to google it or to see if anyone can help.

**Comment by cyxx** [comment]
I ran into the same issue today, using python 2.7 (the code is fine with python 3.x as it includes https://www.python.org/dev/peps/pep-3132/).

A possible workaround is 

```
-  self.model = B.sequential(fea_conv, B.ShortcutBlock(B.sequential(*rb_blocks, LR_conv)),\
-      *upsampler, HR_conv0, HR_conv1)
+  self.model = B.sequential(fea_conv, B.ShortcutBlock(B.sequential(*(rb_blocks + [LR_conv]))),\
+      *(upsampler + [HR_conv0, HR_conv1]))

```

**Comment by cyxx** [comment]
I met the same issue today using python 2.7.
With the below diff, I have been able to run test.py -

```
-  self.model = B.sequential(fea_conv, B.ShortcutBlock(B.sequential(*rb_blocks, LR_conv)),\
-      *upsampler, HR_conv0, HR_conv1)
+  self.model = B.sequential(fea_conv, B.ShortcutBlock(B.sequential(*(rb_blocks + [LR_conv]))),\
+      *(upsampler + [HR_conv0, HR_conv1]))

```
