### ISSUE TITLE
Add running at CPU

### ISSUE THREAD

**Issue by Yolkis** [xinntao/ESRGAN#3]
yolkis@YOLKIS:~/ESRGAN$ python3 test.py models/RRDB_ESRGAN_x4.pth
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=74 error=35 : CUDA driver version is insufficient for CUDA runtime version
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    model = model.cuda()
  File "/home/yolkis/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 258, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/yolkis/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home/yolkis/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home/yolkis/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 191, in _apply
    param.data = fn(param.data)
  File "/home/yolkis/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 258, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /pytorch/aten/src/THC/THCGeneral.cpp:74

**Comment by Yolkis** [comment]
Solution: 
change in test.py 
model = model.cuda()
and
img_LR = img_LR.cuda()
to
model = model.cpu()
and
img_LR = img_LR.cpu()

**Comment by xinntao** [comment]
@Yolkis 
Thanks, later I will add support for CPU ;-)

**Comment by zigzati** [comment]
> Solution:
> change in test.py
> model = model.cuda()
> and
> img_LR = img_LR.cuda()
> to
> model = model.cpu()
> and
> img_LR = img_LR.cpu()

I did this (I have AMD GPU on Windows 10) and it crashed my PC (reproducible) when I tried to run the test with the ESRGAN model. All dependencies are installed.

**Comment by xinntao** [comment]
@zigzati 
I have updated the code to run on CPU. It works fine on my Ubuntu PC but it is slow. 
You can have a try.

**Comment by chr2117216003** [comment]
It is too slow when running on windows and CPU. Is there any idea to accelerate that?

**Comment by xinntao** [comment]
@chr2117216003 
use GPU to accelerate.
