### ISSUE TITLE
ESRGAN Doesn't run on GPU "RuntimeError: error in LoadLibraryA"

### ISSUE THREAD

**Issue by Masterbond7** [xinntao/ESRGAN#94]
Sorry, I am new to CUDA and things like this but every time I want to run ESRGAN on my GPU it gives me this error. Works fine on CPU.

Full output:
============================== RESTART: C:\Users\Masterbond7\Desktop\ESRGAN-master\test.py =============================
Model path models/RRDB_ESRGAN_x4.pth. 
Testing...
1 baboon
Traceback (most recent call last):
  File "C:\Users\Masterbond7\Desktop\ESRGAN-master\test.py", line 34, in <module>
    output = model(img_LR).data.squeeze().float().cpu().clamp_(0, 1).numpy()
  File "C:\Users\Masterbond7\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Masterbond7\Desktop\ESRGAN-master\RRDBNet_arch.py", line 71, in forward
    trunk = self.trunk_conv(self.RRDB_trunk(fea))
  File "C:\Users\Masterbond7\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Masterbond7\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\container.py", line 100, in forward
    input = module(input)
  File "C:\Users\Masterbond7\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Masterbond7\Desktop\ESRGAN-master\RRDBNet_arch.py", line 47, in forward
    out = self.RDB1(x)
  File "C:\Users\Masterbond7\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Masterbond7\Desktop\ESRGAN-master\RRDBNet_arch.py", line 30, in forward
    x2 = self.lrelu(self.conv2(torch.cat((x, x1), 1)))
RuntimeError: error in LoadLibraryA

**Comment by RuStAk** [comment]
You're probably running the latest version of Python. I had the same error until I downgraded to Python 3.7.5 and now it works.

**Comment by rlaPHOENiX** [comment]
Python 3.8.1 on latest CUDA and latest NVIDIA drivers works for me.
I'm on arch linux with everything up to date.

**Comment by autofasurer** [comment]
Put this after importing torch:

```
import ctypes
ctypes.cdll.LoadLibrary('caffe2_nvrtc.dll')

```

**Comment by Dhawaleswrar** [comment]
> Put this after importing torch:
> 
> ```
> import ctypes
> ctypes.cdll.LoadLibrary('caffe2_nvrtc.dll')
> ```

It's working now..Thank you..
